### ISSUE TITLE
Error with Packer (before adding Expansion)

### ISSUE THREAD

**Issue by bafread** [paseaf/containerSSH-honeypot#18] opened 2022-06-04 11:39 UTC
![image](https://user-images.githubusercontent.com/106653277/171997340-2c3f44d1-8c7d-47ff-9a9e-dd1c0bbd4a02.png)

the strange error, come sometimes. I'll just ignore it for now and implement the other stuff for now, but would be cool if we could fix it, so it becomemore stabile. :)

**Comment by paseaf** [comment] 2022-06-04 13:34
Is this duplicate of #10 ?

**Comment by bafread** [comment] 2022-06-04 15:02
no it's something else. But now it's fixed :)
1. Failed to build issue due: disconnected -> fixed now (change the reboot to shutdown + wait)
2. Failed to build issue due: sometimes /tmp/util_fn not found -> fixed now (change the folder now to /home/tmp/)

**Comment by bafread** [comment] 2022-06-04 15:12
After Merge Packer folder with another branch, the issue should be fixed.

**Closed** 2022-06-11 19:31 UTC
Labels: bug, invalid, packer

**Comment by paseaf** [comment] 2022-06-12 12:59
> 2. Failed to build issue due: sometimes /tmp/util_fn not found -> fixed now (change the folder now to /home/tmp/)

Just realized that it is an actually an expected behavior. `/tmp` is cleaned after reboot, so you need to copy the file again after reboot if using `/tmp` directory
